auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title: "HTML Dog 中文翻译"
description: "HTML, CSS, JavaScript 教程, 手册, 文章 | HTML Dog 中文翻译"
domain: https://github.com/yanguanglan/htmldogcn.github.io
baseurl: /
production_url: https://github.com/yanguanglan/htmldogcn.github.io

author :
  lan : "Lan"
  julytalk: "Julytalk"

